### ISSUE TITLE
JDBC Connection

### ISSUE THREAD

**Issue by pupupulp** [evosec/metabase-firebird-driver#1]
Hi I've been having a problem when registering a database using the driver it says that

**No suitable driver found for jdbc:firebirdsql://HOST:PORT/DB**

I already followed your steps on the readme and also checked if the permissions are set correctly

-rw-r--r--    1 metabase metabase    301604 Aug 14 04:43 bigquery.metabase-driver.jar
-rw-r--r--    1 metabase metabase    431502 Aug 14 04:43 druid.metabase-driver.jar
-rw-r--r--    1 metabase metabase   1593175 Aug 14 04:29 firebird.metabase-driver.jar
-rw-r--r--    1 metabase metabase   3054092 Aug 14 04:43 google.metabase-driver.jar
-rw-r--r--    1 metabase metabase    603402 Aug 14 04:43 googleanalytics.metabase-driver.jar
-rw-r--r--    1 metabase metabase   6484826 Aug 14 04:43 mongo.metabase-driver.jar
-rw-r--r--    1 metabase metabase     63696 Aug 14 04:43 oracle.metabase-driver.jar
-rw-r--r--    1 metabase metabase    139356 Aug 14 04:43 presto.metabase-driver.jar
-rw-r--r--    1 metabase metabase   2344224 Aug 14 04:43 redshift.metabase-driver.jar
-rw-r--r--    1 metabase metabase  15751541 Aug 14 04:43 snowflake.metabase-driver.jar
-rw-r--r--    1 metabase metabase  64214128 Aug 14 04:43 sparksql.metabase-driver.jar
-rw-r--r--    1 metabase metabase   7105660 Aug 14 04:43 sqlite.metabase-driver.jar
-rw-r--r--    1 metabase metabase   1177285 Aug 14 04:43 sqlserver.metabase-driver.jar
-rw-r--r--    1 metabase metabase     46161 Aug 14 04:43 vertica.metabase-driver.jar

here are the plugins everything seems correct but still i cant register a database, i was wondering what could be the cause, I also setup jaybird as jdbc driver correct me if there is something wrong with my jdbc driver setup for i am a bit doubtful on that part

im running metabase on docker btw

here is the **Dockerfile**

```
FROM metabase/metabase

ENV FB_DRIVER_URL=https://github.com/evosec/metabase-firebird-driver/releases/download/v1.0/firebird.metabase-driver.jar \
    FB_DRIVER=firebird.metabase-driver.jar \
    PLUGINS_PATH=/plugins   
 
COPY setup-user-group.sh setup-user-group.sh
COPY jaybird-3.0.6.jar /usr/java/jaybird-3.0.6.jar
COPY jaybird-full-3.0.6.jar /usr/java/jaybird-full-3.0.6.jar

ENV CLASSPATH "${CLASSPATH}:/usr/java/jaybird-3.0.6.jar"
ENV CLASSPATH "${CLASSPATH}:/usr/java/jaybird-full-3.0.6.jar"

RUN chmod +x setup-user-group.sh \
    && ./setup-user-group.sh

RUN wget -O ${PLUGINS_PATH}/${FB_DRIVER} ${FB_DRIVER_URL}

RUN chmod 644 ${PLUGINS_PATH}/${FB_DRIVER} \
    && chown metabase:metabase ${PLUGINS_PATH}/${FB_DRIVER}

ENTRYPOINT ["/app/run_metabase.sh"]
```

and here is the **docker-compose** file

```
version: '3'
services:
  metabase:
    image: custom/metabase:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 120s
      placement:
        constraints: [node.role == manager]
    environment:
      - MB_DB_FILE=/var/lib/metabase/data/metabase.db
    ports:
      - 8082:3000
    volumes:
      - metabase_data:/var/lib/metabase/data
networks:
  default:
    external:
      name: tools_services
volumes:
  metabase_data:
    external: true
```

looking forward for your help thank you so much
